[core] avoid exception in k8s adaptor __del__ (#7699)
Before this change, you can see
```
Exception ignored in: <function ClientWrapper.__del__ at 0x7f5322771ea0>
Traceback (most recent call last):
  File "/skypilot/sky/adaptors/kubernetes.py", line 201, in __del__
AttributeError: 'NoneType' object has no attribute 'debug'
Exception ignored in: <function ClientWrapper.__del__ at 0x7f5322771ea0>
Traceback (most recent call last):
  File "/skypilot/sky/adaptors/kubernetes.py", line 201, in __del__
AttributeError: 'NoneType' object has no attribute 'debug'
```

This is due to [how __del__
works](https://docs.python.org/3/reference/datamodel.html#object.__del__),
where other globals may already be unloaded.

> __del__() can be executed during interpreter shutdown. As a
> consequence, the global variables it needs to access (including
> other modules) may already have been deleted or set to None. Python
> guarantees that globals whose name begins with a single underscore
> are deleted from their module before other globals are deleted; if
> no other references to such globals exist, this may help in assuring
> that imported modules are still available at the time when the
> __del__() method is called.

In this case, we shouldn't worry too much about the exception and just
continue.